// Mocks generated by Mockito 5.1.0 from annotations
// in random_data/test/startup_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:random_data/core/data_sources/remote_data_source/remote_data_source.dart'
    as _i3;
import 'package:random_data/core/models/client_transactions.dart' as _i6;
import 'package:random_data/core/models/transactions.dart' as _i7;
import 'package:random_data/core/utils/exports.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock implements _i3.RemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AppError, List<_i6.ClientTransactions>>>
      fetchTransactions() => (super.noSuchMethod(
          Invocation.method(#fetchTransactions, []),
          returnValue: Future<
                  _i2.Either<_i5.AppError, List<_i6.ClientTransactions>>>.value(
              _FakeEither_0<_i5.AppError, List<_i6.ClientTransactions>>())) as _i4
          .Future<_i2.Either<_i5.AppError, List<_i6.ClientTransactions>>>);
}

/// A class which mocks [Transactions].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactions extends _i1.Mock implements _i7.Transactions {
  MockTransactions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set clientTransactions(List<_i6.ClientTransactions>? _clientTransactions) =>
      super.noSuchMethod(
          Invocation.setter(#clientTransactions, _clientTransactions),
          returnValueForMissingStub: null);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}

/// A class which mocks [ClientTransactions].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientTransactions extends _i1.Mock
    implements _i6.ClientTransactions {
  MockClientTransactions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set transactionId(int? _transactionId) =>
      super.noSuchMethod(Invocation.setter(#transactionId, _transactionId),
          returnValueForMissingStub: null);
  @override
  set type(String? _type) => super.noSuchMethod(Invocation.setter(#type, _type),
      returnValueForMissingStub: null);
  @override
  set amount(double? _amount) =>
      super.noSuchMethod(Invocation.setter(#amount, _amount),
          returnValueForMissingStub: null);
  @override
  set comment(String? _comment) =>
      super.noSuchMethod(Invocation.setter(#comment, _comment),
          returnValueForMissingStub: null);
  @override
  set entryDate(String? _entryDate) =>
      super.noSuchMethod(Invocation.setter(#entryDate, _entryDate),
          returnValueForMissingStub: null);
  @override
  set currencyCode(String? _currencyCode) =>
      super.noSuchMethod(Invocation.setter(#currencyCode, _currencyCode),
          returnValueForMissingStub: null);
  @override
  set balance(String? _balance) =>
      super.noSuchMethod(Invocation.setter(#balance, _balance),
          returnValueForMissingStub: null);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}
